### ISSUE TITLE
python3中createPrivateSignature报错 

### ISSUE THREAD

**Issue by eryk** [huobiapi/REST-API-demos#25]
```
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "D:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/workspaces/python/skymind_python/skymind/mdf/huobi/exchange.py", line 1044, in <module>
    print(client.get_account_info())
  File "D:/workspaces/python/skymind_python/skymind/mdf/huobi/exchange.py", line 325, in get_account_info
    ret = self.rest.api_key_get(params, path)
  File "D:\workspaces\python\skymind_python\skymind\mdf\huobi\rest_client.py", line 110, in api_key_get
    params['PrivateSignature'] = self.createPrivateSignature(params['Signature'])
  File "D:\workspaces\python\skymind_python\skymind\mdf\huobi\rest_client.py", line 157, in createPrivateSignature
    skey = load_pem_private_key(self.private_key, password=None, backend=default_backend())
  File "D:\anaconda\lib\site-packages\cryptography\hazmat\primitives\serialization.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "D:\anaconda\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1014, in load_pem_private_key
    password,
  File "D:\anaconda\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1233, in _load_key
    self._handle_key_loading_error()
  File "D:\anaconda\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1291, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.

```

**Comment by karalex** [comment]
![karalex](https://user-images.githubusercontent.com/11707867/42743726-0c924534-88cf-11e8-996c-1efbb08816ec.png)
